import * as esbuild from "esbuild"
import { existsSync, readFileSync, writeFileSync } from "fs"
import { resolve } from "path"
import { solidPlugin } from "esbuild-plugin-solid"

// Generate src/_version.ts when missing (not tracked in git; generated by
// the "version" npm script on release).  Without it the bundle build fails.
const versionFile = resolve("src/_version.ts")
if (!existsSync(versionFile)) {
  const pkg = JSON.parse(readFileSync("package.json", "utf-8"))
  writeFileSync(versionFile, `// auto-generated\r\nexport const PLUGIN_VERSION=${JSON.stringify(pkg.version)};\r\n`)
}

await esbuild.build({
  entryPoints: ["src/index.tsx"],
  outfile: "dist/tui.js",
  format: "esm",
  platform: "node",
  bundle: true,
  external: ["@opencode-ai/*", "@opencode/plugin/*", "@opentui/*", "solid-js"],
  plugins: [solidPlugin({ solid: { moduleName: "@opentui/solid", generate: "universal" } })],
})

// V2（opencode 2.x）入口：{ id, setup } 协议，独立产物。
// @opentui/* + solid-js 保持 external：必须用 V2 宿主的同一实例（renderer 上下文相通——
// self-contained 内联会导致 "No renderer found"）。@opencode-ai/*、@opencode/plugin/* 仅
// type-only（编译擦除），列出 external 以防误引入。
await esbuild.build({
  entryPoints: ["src/v2/index.tsx"],
  outfile: "dist/v2.js",
  format: "esm",
  platform: "node",
  bundle: true,
  external: ["@opencode-ai/*", "@opencode/plugin/*", "@opentui/*", "solid-js"],
  plugins: [solidPlugin({ solid: { moduleName: "@opentui/solid", generate: "universal" } })],
})
